### ISSUE TITLE
Support a default set of prefixes

### ISSUE THREAD

**Issue by nikkiwd** [ad-freiburg/qlever-ui#61]
When I try to write queries in https://qlever.cs.uni-freiburg.de/wikidata/, it's really annoying because I have to manually look up all the prefixes I need. It doesn't even provide a list of common prefixes I can pick from, I have to go to other sites to find out what they should be.

[This query](https://qlever.cs.uni-freiburg.de/wikidata/acxrbw), for example, gives the error `Invalid SPARQL query: Prefix skos was not registered using a PREFIX declaration`.

https://query.wikidata.org/ on the other hand automatically includes a default set of prefixes which covers the vast majority of queries I write, which makes it much easier to use.

Some people have claimed that QLever does automatically add prefixes but it has never done that for me.

**Comment by hannahbast** [comment]
@nikkiwd The QLever UI automatically adds all the prefixes in all situations, whether you are typing, accepting a suggestion, or copying and pasting a query without prefixes from somewhere else. Again, the only reason that happened for your query is because the `SELECT` is not all uppercase. But this is one issue and not many so I am closing this one.
